<?php
    $lang['number']   = 'Reservierungsnummer';
    $lang['date']     = 'Reservierungsdatum';
    $lang['time']     = 'Bestätigungsdatum';
    $lang['due']      = 'Zahlungsziel';
    $lang['to']       = 'Empfänger';
    $lang['from']     = 'Ausgabe durch';
    $lang['product']  = 'Karte';
    $lang['qty']      = 'Menge';
    $lang['price']    = 'Preis';
    $lang['discount'] = 'Rabatt';
    $lang['vat']      = 'MwSt';
    $lang['total']    = 'Gesamtbetrag';
    $lang['page']     = 'Seite';
    $lang['page_of']  = 'von';
